import type {
  GovernanceProposal,
  ManagerProfile,
  Strategy,
  Vault,
  VeLockView,
} from "atlas-types";

export const seedManagers: ManagerProfile[] = [
  {
    id: "mgr_quantum",
    owner: "HoPrXWPH3naKVZEftnckQVpd2bSNRnSiFS2TysDiv5Ff",
    name: "Quantum Capital",
    status: "active",
    score: {
      feeGeneration: 78,
      risk: 22,
      drawdown: 18,
      capitalRetention: 88,
      consistency: 82,
      tvlGrowth: 74,
      governanceParticipation: 60,
      total: 79,
    },
    bondAmount: 500_000,
    tvl: 12_400_000,
    assetsUnderManagement: 12_400_000,
    pnl: 1_850_000,
    maxDrawdown: 0.06,
    feesGenerated: 240_000,
    poolsTraded: 14,
    protocolsUsed: ["meteora", "orca", "raydium", "kamino"],
    yearsActive: 2,
    createdAt: Date.now() - 730 * 86_400_000,
    updatedAt: Date.now() - 86_400_000,
  },
  {
    id: "mgr_apex",
    owner: "9PcknAvu4Vou8xiYXBErfLkv4irKGucPszaguEFFvexr",
    name: "Apex Liquidity",
    status: "active",
    score: {
      feeGeneration: 85,
      risk: 30,
      drawdown: 24,
      capitalRetention: 76,
      consistency: 70,
      tvlGrowth: 92,
      governanceParticipation: 45,
      total: 77,
    },
    bondAmount: 300_000,
    tvl: 8_700_000,
    assetsUnderManagement: 8_700_000,
    pnl: 1_200_000,
    maxDrawdown: 0.09,
    feesGenerated: 310_000,
    poolsTraded: 9,
    protocolsUsed: ["meteora", "drift", "jupiter"],
    yearsActive: 1,
    createdAt: Date.now() - 400 * 86_400_000,
    updatedAt: Date.now() - 3 * 86_400_000,
  },
  {
    id: "mgr_harbor",
    owner: "4emaasdjZe2JhDTWSrXYSkyHniGQFmkZ5ias2fjAWp6n",
    name: "Harbor Stable",
    status: "active",
    score: {
      feeGeneration: 65,
      risk: 12,
      drawdown: 8,
      capitalRetention: 94,
      consistency: 90,
      tvlGrowth: 58,
      governanceParticipation: 80,
      total: 80,
    },
    bondAmount: 400_000,
    tvl: 18_200_000,
    assetsUnderManagement: 18_200_000,
    pnl: 890_000,
    maxDrawdown: 0.02,
    feesGenerated: 180_000,
    poolsTraded: 6,
    protocolsUsed: ["kamino", "marginfi", "sanctum"],
    yearsActive: 3,
    createdAt: Date.now() - 1100 * 86_400_000,
    updatedAt: Date.now() - 2 * 86_400_000,
  },
  {
    id: "mgr_volta",
    owner: "7rWLrzA38Tct6vuuum7quvNMcL4EvAtDsgBm2LEcvusR",
    name: "Volta Volatility",
    status: "active",
    score: {
      feeGeneration: 72,
      risk: 55,
      drawdown: 42,
      capitalRetention: 58,
      consistency: 46,
      tvlGrowth: 66,
      governanceParticipation: 30,
      total: 58,
    },
    bondAmount: 150_000,
    tvl: 3_200_000,
    assetsUnderManagement: 3_200_000,
    pnl: 610_000,
    maxDrawdown: 0.14,
    feesGenerated: 195_000,
    poolsTraded: 11,
    protocolsUsed: ["meteora", "raydium"],
    yearsActive: 1,
    createdAt: Date.now() - 320 * 86_400_000,
    updatedAt: Date.now() - 86_400_000,
  },
  {
    id: "mgr_nova",
    owner: "8pW6VEM8xHGzaSuVSBByvkCFsyBmgHBJvddTGwEyrGoG",
    name: "Nova Basket",
    status: "suspended",
    score: {
      feeGeneration: 60,
      risk: 70,
      drawdown: 58,
      capitalRetention: 40,
      consistency: 35,
      tvlGrowth: 50,
      governanceParticipation: 20,
      total: 48,
    },
    bondAmount: 50_000,
    tvl: 900_000,
    assetsUnderManagement: 900_000,
    pnl: -120_000,
    maxDrawdown: 0.22,
    feesGenerated: 90_000,
    poolsTraded: 7,
    protocolsUsed: ["raydium"],
    yearsActive: 0,
    createdAt: Date.now() - 180 * 86_400_000,
    updatedAt: Date.now() - 10 * 86_400_000,
  },
];

export const seedStrategies: Strategy[] = [
  {
    id: "str_btc_sol_conservative",
    managerId: "mgr_quantum",
    name: "BTC/SOL Conservative",
    type: "passive",
    protocol: "meteora",
    pool: "BTC-SOL DLMM",
    pair: "BTC/SOL",
    tvl: 5_100_000,
    apy: 14.2,
    apr: 13.8,
    maxDrawdown: 0.05,
    sharpeRatio: 1.9,
    sortinoRatio: 2.6,
    fees: { managementBps: 50, performanceBps: 1500 },
    impermanentLoss: 0.018,
    utilization: 0.82,
    ageDays: 420,
    version: 3,
    riskTier: 1,
  },
  {
    id: "str_sol_usdc_active",
    managerId: "mgr_apex",
    name: "SOL/USDC Active",
    type: "active",
    protocol: "meteora",
    pool: "SOL-USDC DLMM",
    pair: "SOL/USDC",
    tvl: 6_400_000,
    apy: 22.7,
    apr: 24.1,
    maxDrawdown: 0.08,
    sharpeRatio: 1.6,
    sortinoRatio: 2.1,
    fees: { managementBps: 75, performanceBps: 2000 },
    impermanentLoss: 0.031,
    utilization: 0.88,
    ageDays: 310,
    version: 5,
    riskTier: 2,
  },
  {
    id: "str_sol_usdc_dlmm",
    managerId: "mgr_quantum",
    name: "SOL/USDC DLMM",
    type: "passive",
    protocol: "meteora",
    pool: "SOL-USDC DLMM",
    pair: "SOL/USDC",
    tvl: 8_200_000,
    apy: 19.4,
    apr: 18.7,
    maxDrawdown: 0.045,
    sharpeRatio: 2.1,
    sortinoRatio: 2.8,
    fees: { managementBps: 45, performanceBps: 1200 },
    impermanentLoss: 0.022,
    utilization: 0.85,
    ageDays: 380,
    version: 4,
    riskTier: 2,
  },
  {
    id: "str_usdt_usdc_dlmm",
    managerId: "mgr_harbor",
    name: "USDT/USDC Stable DLMM",
    type: "adaptive",
    protocol: "meteora",
    pool: "USDT-USDC DLMM",
    pair: "USDT/USDC",
    tvl: 12_500_000,
    apy: 9.2,
    apr: 9.0,
    maxDrawdown: 0.008,
    sharpeRatio: 3.5,
    sortinoRatio: 5.4,
    fees: { managementBps: 35, performanceBps: 800 },
    impermanentLoss: 0.001,
    utilization: 0.72,
    ageDays: 520,
    version: 6,
    riskTier: 1,
  },
  {
    id: "str_jup_sol_dlmm",
    managerId: "mgr_apex",
    name: "JUP/SOL DLMM",
    type: "active",
    protocol: "meteora",
    pool: "JUP-SOL DLMM",
    pair: "JUP/SOL",
    tvl: 3_800_000,
    apy: 34.5,
    apr: 36.2,
    maxDrawdown: 0.12,
    sharpeRatio: 1.3,
    sortinoRatio: 1.7,
    fees: { managementBps: 80, performanceBps: 2200 },
    impermanentLoss: 0.055,
    utilization: 0.91,
    ageDays: 180,
    version: 2,
    riskTier: 3,
  },
  {
    id: "str_jup_usdc_dlmm",
    managerId: "mgr_quantum",
    name: "JUP/USDC DLMM",
    type: "passive",
    protocol: "meteora",
    pool: "JUP-USDC DLMM",
    pair: "JUP/USDC",
    tvl: 4_600_000,
    apy: 16.8,
    apr: 16.2,
    maxDrawdown: 0.06,
    sharpeRatio: 1.8,
    sortinoRatio: 2.4,
    fees: { managementBps: 50, performanceBps: 1400 },
    impermanentLoss: 0.028,
    utilization: 0.83,
    ageDays: 290,
    version: 3,
    riskTier: 2,
  },
  {
    id: "str_met_sol_dlmm",
    managerId: "mgr_volta",
    name: "MET/SOL DLMM",
    type: "active",
    protocol: "meteora",
    pool: "MET-SOL DLMM",
    pair: "MET/SOL",
    tvl: 2_900_000,
    apy: 41.2,
    apr: 43.8,
    maxDrawdown: 0.16,
    sharpeRatio: 1.0,
    sortinoRatio: 1.3,
    fees: { managementBps: 90, performanceBps: 2500 },
    impermanentLoss: 0.072,
    utilization: 0.93,
    ageDays: 120,
    version: 2,
    riskTier: 4,
  },
  {
    id: "str_met_usdc_dlmm",
    managerId: "mgr_harbor",
    name: "MET/USDC DLMM",
    type: "scheduled",
    protocol: "meteora",
    pool: "MET-USDC DLMM",
    pair: "MET/USDC",
    tvl: 5_300_000,
    apy: 15.6,
    apr: 15.1,
    maxDrawdown: 0.07,
    sharpeRatio: 1.7,
    sortinoRatio: 2.2,
    fees: { managementBps: 55, performanceBps: 1600 },
    impermanentLoss: 0.035,
    utilization: 0.80,
    ageDays: 350,
    version: 4,
    riskTier: 2,
  },
  {
    id: "str_meme_basket",
    managerId: "mgr_volta",
    name: "Meme Basket",
    type: "rule-based",
    protocol: "raydium",
    pool: "Multi-pair CLMM",
    pair: "MEME Basket",
    tvl: 2_100_000,
    apy: 48.3,
    apr: 52.0,
    maxDrawdown: 0.19,
    sharpeRatio: 0.9,
    sortinoRatio: 1.1,
    fees: { managementBps: 100, performanceBps: 2500 },
    impermanentLoss: 0.085,
    utilization: 0.91,
    ageDays: 140,
    version: 2,
    riskTier: 4,
  },
  {
    id: "str_stable_yield",
    managerId: "mgr_harbor",
    name: "Stable Yield",
    type: "adaptive",
    protocol: "kamino",
    pool: "USDC-USDT",
    pair: "USDC/USDT",
    tvl: 14_800_000,
    apy: 8.9,
    apr: 8.7,
    maxDrawdown: 0.012,
    sharpeRatio: 3.2,
    sortinoRatio: 5.1,
    fees: { managementBps: 40, performanceBps: 1000 },
    impermanentLoss: 0.002,
    utilization: 0.76,
    ageDays: 890,
    version: 7,
    riskTier: 1,
  },
  {
    id: "str_vol_capture",
    managerId: "mgr_apex",
    name: "Volatility Capture",
    type: "ai-assisted",
    protocol: "drift",
    pool: "SOL-PERP",
    pair: "SOL/PERP",
    tvl: 2_300_000,
    apy: 31.5,
    apr: 33.9,
    maxDrawdown: 0.12,
    sharpeRatio: 1.2,
    sortinoRatio: 1.5,
    fees: { managementBps: 90, performanceBps: 2000 },
    impermanentLoss: 0.045,
    utilization: 0.85,
    ageDays: 200,
    version: 4,
    riskTier: 3,
  },
  {
    id: "str_range_rotation",
    managerId: "mgr_quantum",
    name: "Range Rotation",
    type: "scheduled",
    protocol: "orca",
    pool: "SOL-USDC CLMM",
    pair: "SOL/USDC",
    tvl: 4_300_000,
    apy: 18.4,
    apr: 18.9,
    maxDrawdown: 0.06,
    sharpeRatio: 1.8,
    sortinoRatio: 2.3,
    fees: { managementBps: 60, performanceBps: 1500 },
    impermanentLoss: 0.024,
    utilization: 0.79,
    ageDays: 500,
    version: 3,
    riskTier: 2,
  },
  {
    id: "str_jupiter_liquidity",
    managerId: "mgr_apex",
    name: "Jupiter Liquidity",
    type: "passive",
    protocol: "jupiter",
    pool: "Jupiter Aggregator",
    pair: "Multi-pair",
    tvl: 7_200_000,
    apy: 12.8,
    apr: 12.3,
    maxDrawdown: 0.035,
    sharpeRatio: 2.4,
    sortinoRatio: 3.1,
    fees: { managementBps: 40, performanceBps: 1000 },
    impermanentLoss: 0.012,
    utilization: 0.78,
    ageDays: 450,
    version: 5,
    riskTier: 1,
  },
  {
    id: "str_sanctum_liquid",
    managerId: "mgr_harbor",
    name: "Sanctum Liquid",
    type: "adaptive",
    protocol: "sanctum",
    pool: "Liquid Staking",
    pair: "SOL/LST",
    tvl: 9_100_000,
    apy: 11.3,
    apr: 10.9,
    maxDrawdown: 0.015,
    sharpeRatio: 3.0,
    sortinoRatio: 4.2,
    fees: { managementBps: 35, performanceBps: 900 },
    impermanentLoss: 0.003,
    utilization: 0.68,
    ageDays: 620,
    version: 4,
    riskTier: 1,
  },
  {
    id: "str_marinade_stake",
    managerId: "mgr_quantum",
    name: "Marinade Staking",
    type: "passive",
    protocol: "marinade",
    pool: "MSOL Staking",
    pair: "SOL/mSOL",
    tvl: 5_700_000,
    apy: 7.4,
    apr: 7.2,
    maxDrawdown: 0.005,
    sharpeRatio: 3.8,
    sortinoRatio: 5.5,
    fees: { managementBps: 30, performanceBps: 750 },
    impermanentLoss: 0.001,
    utilization: 0.65,
    ageDays: 750,
    version: 6,
    riskTier: 1,
  },
  {
    id: "str_orca_concentrated",
    managerId: "mgr_volta",
    name: "Orca Concentrated",
    type: "active",
    protocol: "orca",
    pool: "SOL-USDC CLMM",
    pair: "SOL/USDC",
    tvl: 3_100_000,
    apy: 25.6,
    apr: 26.1,
    maxDrawdown: 0.09,
    sharpeRatio: 1.5,
    sortinoRatio: 1.9,
    fees: { managementBps: 70, performanceBps: 1800 },
    impermanentLoss: 0.038,
    utilization: 0.87,
    ageDays: 200,
    version: 3,
    riskTier: 3,
  },
  {
    id: "str_raydium_clmm",
    managerId: "mgr_nova",
    name: "Raydium CLMM",
    type: "rule-based",
    protocol: "raydium",
    pool: "RAY-USDC CLMM",
    pair: "RAY/USDC",
    tvl: 1_800_000,
    apy: 28.9,
    apr: 30.2,
    maxDrawdown: 0.15,
    sharpeRatio: 1.1,
    sortinoRatio: 1.4,
    fees: { managementBps: 85, performanceBps: 2300 },
    impermanentLoss: 0.065,
    utilization: 0.89,
    ageDays: 90,
    version: 2,
    riskTier: 3,
  },
];

export const seedVaults: Vault[] = [
  {
    address: "VaU1tXYb7mX8G5w3eRkQzKj4nLpDcVfBqHtSwXcYaZx",
    name: "Atlas Core Yield",
    baseAsset: "USDC",
    managerId: "mgr_quantum",
    authority: "AtL45sAu2DvBqPj9nRyGcE7fHwMzNxQkTpSrLvJmWcYa",
    status: "active",
    tvl: 31_000_000,
    apy: 17.5,
    sharesOutstanding: 28_000_000,
    managementFeeBps: 50,
    performanceFeeBps: 2000,
    minDeposit: 100,
    allocation: null,
    createdAt: Date.now() - 400 * 86_400_000,
    lastRebalanceAt: Date.now() - 3_600_000,
  },
  {
    address: "VaU2tXYb7mX8G5w3eRkQzKj4nLpDcVfBqHtSwXcYaZx",
    name: "Atlas Stable Reserve",
    baseAsset: "USDT",
    managerId: "mgr_harbor",
    authority: "AtL45sAu2DvBqPj9nRyGcE7fHwMzNxQkTpSrLvJmWcYa",
    status: "active",
    tvl: 14_500_000,
    apy: 8.9,
    sharesOutstanding: 13_000_000,
    managementFeeBps: 40,
    performanceFeeBps: 1000,
    minDeposit: 100,
    allocation: null,
    createdAt: Date.now() - 700 * 86_400_000,
    lastRebalanceAt: Date.now() - 86_400_000,
  },
  {
    address: "VaU3tXYb7mX8G5w3eRkQzKj4nLpDcVfBqHtSwXcYaZx",
    name: "Atlas Vol Alpha",
    baseAsset: "SOL",
    managerId: "mgr_apex",
    authority: "AtL45sAu2DvBqPj9nRyGcE7fHwMzNxQkTpSrLvJmWcYa",
    status: "active",
    tvl: 6_800_000,
    apy: 26.1,
    sharesOutstanding: 5_200_000,
    managementFeeBps: 75,
    performanceFeeBps: 2000,
    minDeposit: 500,
    allocation: null,
    createdAt: Date.now() - 260 * 86_400_000,
    lastRebalanceAt: Date.now() - 30 * 60 * 1000,
  },
  {
    address: "VaU4tXYb7mX8G5w3eRkQzKj4nLpDcVfBqHtSwXcYaZx",
    name: "Atlas Momentum",
    baseAsset: "SOL",
    managerId: "mgr_volta",
    authority: "AtL45sAu2DvBqPj9nRyGcE7fHwMzNxQkTpSrLvJmWcYa",
    status: "active",
    tvl: 3_400_000,
    apy: 31.2,
    sharesOutstanding: 2_900_000,
    managementFeeBps: 90,
    performanceFeeBps: 2500,
    minDeposit: 250,
    allocation: null,
    createdAt: Date.now() - 200 * 86_400_000,
    lastRebalanceAt: Date.now() - 7_200_000,
  },
  {
    address: "VaU5tXYb7mX8G5w3eRkQzKj4nLpDcVfBqHtSwXcYaZx",
    name: "Atlas Meteora Yield",
    baseAsset: "USDC",
    managerId: "mgr_quantum",
    authority: "AtL45sAu2DvBqPj9nRyGcE7fHwMzNxQkTpSrLvJmWcYa",
    status: "active",
    tvl: 18_700_000,
    apy: 21.3,
    sharesOutstanding: 15_200_000,
    managementFeeBps: 55,
    performanceFeeBps: 1800,
    minDeposit: 100,
    allocation: null,
    createdAt: Date.now() - 300 * 86_400_000,
    lastRebalanceAt: Date.now() - 720_000,
  },
  {
    address: "VaU6tXYb7mX8G5w3eRkQzKj4nLpDcVfBqHtSwXcYaZx",
    name: "Atlas DLMM Core",
    baseAsset: "SOL",
    managerId: "mgr_apex",
    authority: "AtL45sAu2DvBqPj9nRyGcE7fHwMzNxQkTpSrLvJmWcYa",
    status: "active",
    tvl: 9_300_000,
    apy: 28.7,
    sharesOutstanding: 7_100_000,
    managementFeeBps: 65,
    performanceFeeBps: 2200,
    minDeposit: 200,
    allocation: null,
    createdAt: Date.now() - 180 * 86_400_000,
    lastRebalanceAt: Date.now() - 1_800_000,
  },
];

export const seedLocks: VeLockView[] = [
  {
    holder: seedManagers[0].owner,
    amount: 500_000,
    weight: 1_250_000,
    unlockAt: Math.floor(Date.now() / 1000) + 400 * 86_400,
    swept: false,
  },
  {
    holder: seedManagers[1].owner,
    amount: 300_000,
    weight: 750_000,
    unlockAt: Math.floor(Date.now() / 1000) + 200 * 86_400,
    swept: false,
  },
  {
    holder: seedManagers[2].owner,
    amount: 1_000_000,
    weight: 2_500_000,
    unlockAt: Math.floor(Date.now() / 1000) + 900 * 86_400,
    swept: false,
  },
  {
    holder: seedManagers[3].owner,
    amount: 200_000,
    weight: 500_000,
    unlockAt: Math.floor(Date.now() / 1000) + 365 * 86_400,
    swept: false,
  },
  {
    holder: seedManagers[4].owner,
    amount: 75_000,
    weight: 187_500,
    unlockAt: Math.floor(Date.now() / 1000) + 90 * 86_400,
    swept: false,
  },
];

export const seedProposals: GovernanceProposal[] = [
  {
    id: "1",
    proposer: seedManagers[0].owner,
    class: "parametric",
    title: "Lower max_per_protocol exposure to 35%",
    targetProgram: "9h29CPwoYFgQ4wYN2oWWCyA9rS3nMYaeS99Y676zSGa8",
    instructionData: "",
    quorumWeight: 225_000,
    forVotes: 1_100_000,
    againstVotes: 120_000,
    startVotingAt: Math.floor(Date.now() / 1000) - 86_400,
    endVotingAt: Math.floor(Date.now() / 1000) + 3 * 86_400,
    executionAt: 0,
    status: "active",
  },
  {
    id: "2",
    proposer: seedManagers[2].owner,
    class: "fiscal",
    title: "Treasury buyback of 500k ATLAS this month",
    targetProgram: "AbFBCeqqBxpoAGamrPNmrXXMHY5qHybjsoTyYaKJL86q",
    instructionData: "",
    quorumWeight: 450_000,
    forVotes: 2_400_000,
    againstVotes: 300_000,
    startVotingAt: Math.floor(Date.now() / 1000) - 6 * 86_400,
    endVotingAt: Math.floor(Date.now() / 1000) - 86_400,
    executionAt: Math.floor(Date.now() / 1000) + 2 * 86_400,
    status: "succeeded",
  },
  {
    id: "3",
    proposer: seedManagers[1].owner,
    class: "protocol_critical",
    title: "Halt allocations to drift perp strategy",
    targetProgram: "B2sKSyicsc65bJ8AXZigQSfa1MUBiKbBjRqpYQuT6iUA",
    instructionData: "",
    quorumWeight: 675_000,
    forVotes: 300_000,
    againstVotes: 1_900_000,
    startVotingAt: Math.floor(Date.now() / 1000) - 8 * 86_400,
    endVotingAt: Math.floor(Date.now() / 1000) - 86_400,
    executionAt: 0,
    status: "defeated",
  },
  {
    id: "4",
    proposer: seedManagers[0].owner,
    class: "parametric",
    title: "Add MET/USDC DLMM as approved Meteora pool",
    targetProgram: "9h29CPwoYFgQ4wYN2oWWCyA9rS3nMYaeS99Y676zSGa8",
    instructionData: "",
    quorumWeight: 225_000,
    forVotes: 890_000,
    againstVotes: 95_000,
    startVotingAt: Math.floor(Date.now() / 1000) - 43_200,
    endVotingAt: Math.floor(Date.now() / 1000) + 5 * 86_400,
    executionAt: 0,
    status: "active",
  },
  {
    id: "5",
    proposer: seedManagers[3].owner,
    class: "fiscal",
    title: "Allocate 200k ATLAS from treasury to Meteora DLMM incentives",
    targetProgram: "AbFBCeqqBxpoAGamrPNmrXXMHY5qHybjsoTyYaKJL86q",
    instructionData: "",
    quorumWeight: 450_000,
    forVotes: 1_800_000,
    againstVotes: 200_000,
    startVotingAt: Math.floor(Date.now() / 1000) - 2 * 86_400,
    endVotingAt: Math.floor(Date.now() / 1000) + 5 * 86_400,
    executionAt: 0,
    status: "active",
  },
  {
    id: "6",
    proposer: seedManagers[2].owner,
    class: "constitutional",
    title: "Amend governance: reduce quorum for parametric proposals to 3%",
    targetProgram: "5fcfpz4DK8G4HbPMyX259fgotXJaE4v7yNhXidRAtWnD",
    instructionData: "",
    quorumWeight: 675_000,
    forVotes: 3_200_000,
    againstVotes: 150_000,
    startVotingAt: Math.floor(Date.now() / 1000) - 10 * 86_400,
    endVotingAt: Math.floor(Date.now() / 1000) - 3 * 86_400,
    executionAt: Math.floor(Date.now() / 1000) + 27 * 86_400,
    status: "succeeded",
  },
];
